// This file is auto-generated by scripts/gen-renderers.ts
// Do not edit this file directly.

export const rendererManifest: Record<string, string> = {
  'Project_v2': '../components/block_renderers/Project.v2',
  'Task_v2': '../components/block_renderers/Task.v2',
  'Doc_v3': '../components/block_renderers/Doc.v3',
  'Knowledge_v2': '../components/block_renderers/Knowledge.v2',
  'Log_v2': '../components/block_renderers/Log.v2',
};
