// This file is auto-generated by scripts/gen-renderers.ts
// Do not edit this file directly.

export const rendererManifest: Record<string, string> = {
  'Base_v2': '../components/block_renderers/Base.v2.tsx',
  'Project_v2': '../components/block_renderers/Project.v2.tsx',
  'Task_v2': '../components/block_renderers/Task.v2.tsx',
  'Doc_v3': '../components/block_renderers/Doc.v3.tsx',
  'Knowledge_v2': '../components/block_renderers/Knowledge.v2.tsx',
  'Log_v2': '../components/block_renderers/Log.v2.tsx',
};
