/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cogni API
 * A minimal FastAPI that directly passes user queries to OpenAI, augmented with Cogni memory.
 * OpenAPI spec version: 0.1.0
 */
import type { BlocksResponseRequestedBranch } from './blocksResponseRequestedBranch';
import type { MemoryBlock } from './memoryBlock';
import type { BlocksResponseFiltersApplied } from './blocksResponseFiltersApplied';

/**
 * Enhanced response for blocks endpoints that includes branch context.
Uses proper MemoryBlock typing for frontend TypeScript generation.
 */
export interface BlocksResponse {
  /** Currently active Dolt branch for this operation */
  active_branch: string;
  /** Branch requested by client (may differ from active_branch for read operations) */
  requested_branch?: BlocksResponseRequestedBranch;
  /** UTC ISO timestamp when the operation was performed */
  timestamp: string;
  /** List of memory blocks from the requested branch */
  blocks: MemoryBlock[];
  /** Total number of blocks returned */
  total_count: number;
  /** Summary of filters applied (type, case_insensitive, etc.) */
  filters_applied?: BlocksResponseFiltersApplied;
}
