/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cogni API
 * A minimal FastAPI that directly passes user queries to OpenAI, augmented with Cogni memory.
 * OpenAPI spec version: 0.1.0
 */

/**
 * The type of relationship between the blocks
 */
export type BlockLinkRelation = typeof BlockLinkRelation[keyof typeof BlockLinkRelation];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BlockLinkRelation = {
  related_to: 'related_to',
  subtask_of: 'subtask_of',
  depends_on: 'depends_on',
  child_of: 'child_of',
  mentions: 'mentions',
} as const;
