/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cogni API
 * A minimal FastAPI that directly passes user queries to OpenAI, augmented with Cogni memory.
 * OpenAPI spec version: 0.1.0
 */
import type { BlockLinkRelation } from './blockLinkRelation';
import type { BlockLinkPriority } from './blockLinkPriority';
import type { BlockLinkLinkMetadata } from './blockLinkLinkMetadata';
import type { BlockLinkCreatedBy } from './blockLinkCreatedBy';

/**
 * Defines a directed link between two MemoryBlocks.
 */
export interface BlockLink {
  /** ID of the target block in the link */
  to_id: string;
  /** ID of the source block in the link */
  from_id: string;
  /** The type of relationship between the blocks */
  relation: BlockLinkRelation;
  /** Priority of the link (higher numbers = higher priority) */
  priority?: BlockLinkPriority;
  /** Additional metadata about the link */
  link_metadata?: BlockLinkLinkMetadata;
  /** ID of the agent/user who created the link */
  created_by?: BlockLinkCreatedBy;
  /** When the link was created */
  created_at?: string;
}
