/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cogni API
 * A minimal FastAPI that directly passes user queries to OpenAI, augmented with Cogni memory.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Branch requested by client (may differ from active_branch for read operations)
 */
export type BranchesResponseRequestedBranch = string | null;
