/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cogni API
 * A minimal FastAPI that directly passes user queries to OpenAI, augmented with Cogni memory.
 * OpenAPI spec version: 0.1.0
 */
import type { CompleteQueryRequestSystemMessage } from './completeQueryRequestSystemMessage';
import type { CompleteQueryRequestMessageHistory } from './completeQueryRequestMessageHistory';

/**
 * Extended schema for a chat request with additional parameters.
This can be used for more advanced chat endpoints.
 */
export interface CompleteQueryRequest {
  /** The message content to send to the AI */
  message: string;
  /** The AI model to use for generation */
  model?: string;
  /**
   * Controls randomness in the response. Lower is more deterministic.
   * @minimum 0
   * @maximum 1
   */
  temperature?: number;
  /** Instructions for the AI assistant's behavior */
  system_message?: CompleteQueryRequestSystemMessage;
  /** Optional list of previous messages in the conversation */
  message_history?: CompleteQueryRequestMessageHistory;
}
