/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cogni API
 * A minimal FastAPI that directly passes user queries to OpenAI, augmented with Cogni memory.
 * OpenAPI spec version: 0.1.0
 */
import type { ConfidenceScoreHuman } from './confidenceScoreHuman';
import type { ConfidenceScoreAi } from './confidenceScoreAi';

/**
 * Represents confidence scores, potentially from human or AI sources.
 */
export interface ConfidenceScore {
  /** Optional human confidence score (0.0 to 1.0) */
  human?: ConfidenceScoreHuman;
  /** Optional AI-generated confidence score (0.0 to 1.0) */
  ai?: ConfidenceScoreAi;
}
