/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cogni API
 * A minimal FastAPI that directly passes user queries to OpenAI, augmented with Cogni memory.
 * OpenAPI spec version: 0.1.0
 */
import type { CreateMemoryBlockInputState } from './createMemoryBlockInputState';
import type { CreateMemoryBlockInputVisibility } from './createMemoryBlockInputVisibility';
import type { CreateMemoryBlockInputMetadata } from './createMemoryBlockInputMetadata';
import type { CreateMemoryBlockInputSourceFile } from './createMemoryBlockInputSourceFile';
import type { CreateMemoryBlockInputConfidence } from './createMemoryBlockInputConfidence';
import type { CreateMemoryBlockInputCreatedBy } from './createMemoryBlockInputCreatedBy';

/**
 * Input model for creating a new memory block.
 */
export interface CreateMemoryBlockInput {
  /** Type of memory block to create (must be registered in schema registry) */
  type: string;
  /** Primary content of the memory block */
  text: string;
  /** Initial state of the block */
  state?: CreateMemoryBlockInputState;
  /** Visibility level of the block */
  visibility?: CreateMemoryBlockInputVisibility;
  /**
   * Optional tags for filtering and metadata
   * @maxItems 20
   */
  tags?: string[];
  /** Type-specific metadata for the block */
  metadata?: CreateMemoryBlockInputMetadata;
  /** Optional source file or markdown name */
  source_file?: CreateMemoryBlockInputSourceFile;
  /** Optional confidence scores for the block */
  confidence?: CreateMemoryBlockInputConfidence;
  /** Optional identifier for creator (agent name or user ID) */
  created_by?: CreateMemoryBlockInputCreatedBy;
}
