/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cogni API
 * A minimal FastAPI that directly passes user queries to OpenAI, augmented with Cogni memory.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Visibility level of the block
 */
export type CreateMemoryBlockInputVisibility = 'internal' | 'public' | 'restricted' | null;
