/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cogni API
 * A minimal FastAPI that directly passes user queries to OpenAI, augmented with Cogni memory.
 * OpenAPI spec version: 0.1.0
 */
import type { CreateLinkApiV1LinksPostRelation } from './createLinkApiV1LinksPostRelation';

export type CreateLinkApiV1LinksPostParams = {
from_id: string;
to_id: string;
relation: CreateLinkApiV1LinksPostRelation;
priority?: number;
created_by?: string | null;
};
