/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cogni API
 * A minimal FastAPI that directly passes user queries to OpenAI, augmented with Cogni memory.
 * OpenAPI spec version: 0.1.0
 */
import type { DeleteLinkApiV1LinksDeleteRelation } from './deleteLinkApiV1LinksDeleteRelation';

export type DeleteLinkApiV1LinksDeleteParams = {
from_id: string;
to_id: string;
relation: DeleteLinkApiV1LinksDeleteRelation;
};
