/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cogni API
 * A minimal FastAPI that directly passes user queries to OpenAI, augmented with Cogni memory.
 * OpenAPI spec version: 0.1.0
 */

export type DeleteLinkApiV1LinksDeleteRelation = typeof DeleteLinkApiV1LinksDeleteRelation[keyof typeof DeleteLinkApiV1LinksDeleteRelation];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteLinkApiV1LinksDeleteRelation = {
  related_to: 'related_to',
  mentions: 'mentions',
  child_of: 'child_of',
  parent_of: 'parent_of',
  duplicate_of: 'duplicate_of',
  part_of: 'part_of',
  contains: 'contains',
  requires: 'requires',
  provides: 'provides',
  owned_by: 'owned_by',
  owns: 'owns',
  subtask_of: 'subtask_of',
  depends_on: 'depends_on',
  blocks: 'blocks',
  is_blocked_by: 'is_blocked_by',
  belongs_to_epic: 'belongs_to_epic',
  epic_contains: 'epic_contains',
  bug_affects: 'bug_affects',
  has_bug: 'has_bug',
  derived_from: 'derived_from',
  supersedes: 'supersedes',
  references: 'references',
  source_of: 'source_of',
  cited_by: 'cited_by',
} as const;
