/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cogni API
 * A minimal FastAPI that directly passes user queries to OpenAI, augmented with Cogni memory.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Information about a single Dolt branch.
 */
export interface DoltBranchInfo {
  /** Branch name */
  name: string;
  /** Latest commit hash */
  hash: string;
  /** Name of the latest committer */
  latest_committer: string;
  /** Email of the latest committer */
  latest_committer_email: string;
  /** Date of the latest commit */
  latest_commit_date: string;
  /** Message of the latest commit */
  latest_commit_message: string;
  /** Remote name (empty if local) */
  remote: string;
  /** Remote branch name (empty if local) */
  branch: string;
  /** Whether the branch has uncommitted changes */
  dirty: boolean;
}
