/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cogni API
 * A minimal FastAPI that directly passes user queries to OpenAI, augmented with Cogni memory.
 * OpenAPI spec version: 0.1.0
 */
import type { ErrorResponseCode } from './errorResponseCode';

/**
 * Schema for error responses.
 */
export interface ErrorResponse {
  /** A human-readable error message */
  detail: string;
  /** An optional error code for programmatic handling */
  code?: ErrorResponseCode;
}
