/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cogni API
 * A minimal FastAPI that directly passes user queries to OpenAI, augmented with Cogni memory.
 * OpenAPI spec version: 0.1.0
 */

export type GetAllBlocksApiV1BlocksGetParams = {
/**
 * Filter by block type (e.g., 'project', 'knowledge', 'task')
 */
type?: string;
/**
 * Case-insensitive type filtering
 */
case_insensitive?: boolean;
/**
 * Dolt branch to read from (default: 'main')
 */
branch?: string;
};
