/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cogni API
 * A minimal FastAPI that directly passes user queries to OpenAI, augmented with Cogni memory.
 * OpenAPI spec version: 0.1.0
 */

export type GetLinksFromApiV1LinksFromBlockIdGetParams = {
relation?: 'related_to' | 'mentions' | 'child_of' | 'parent_of' | 'duplicate_of' | 'part_of' | 'contains' | 'requires' | 'provides' | 'owned_by' | 'owns' | 'subtask_of' | 'depends_on' | 'blocks' | 'is_blocked_by' | 'belongs_to_epic' | 'epic_contains' | 'bug_affects' | 'has_bug' | 'derived_from' | 'supersedes' | 'references' | 'source_of' | 'cited_by' | null;
depth?: number | null;
direction?: string | null;
limit?: number;
cursor?: string | null;
};
