/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cogni API
 * A minimal FastAPI that directly passes user queries to OpenAI, augmented with Cogni memory.
 * OpenAPI spec version: 0.1.0
 */

/**
 * The role of the message sender.
 */
export type HistoryMessageRole = typeof HistoryMessageRole[keyof typeof HistoryMessageRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HistoryMessageRole = {
  user: 'user',
  assistant: 'assistant',
  system: 'system',
} as const;
