/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cogni API
 * A minimal FastAPI that directly passes user queries to OpenAI, augmented with Cogni memory.
 * OpenAPI spec version: 0.1.0
 */
import type { HistoryMessageRole } from './historyMessageRole';

/**
 * Schema for a single message in the chat history.
 */
export interface HistoryMessage {
  /** The role of the message sender. */
  role: HistoryMessageRole;
  /** The content of the message. */
  content: string;
}
