/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cogni API
 * A minimal FastAPI that directly passes user queries to OpenAI, augmented with Cogni memory.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Version of the schema this block adheres to (links to node_schemas table)
 */
export type MemoryBlockSchemaVersion = number | null;
