/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cogni API
 * A minimal FastAPI that directly passes user queries to OpenAI, augmented with Cogni memory.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Block type used to determine structure and relationships
 */
export type MemoryBlockType = typeof MemoryBlockType[keyof typeof MemoryBlockType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MemoryBlockType = {
  knowledge: 'knowledge',
  task: 'task',
  project: 'project',
  doc: 'doc',
  interaction: 'interaction',
  log: 'log',
  epic: 'epic',
  bug: 'bug',
} as const;
