/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cogni API
 * A minimal FastAPI that directly passes user queries to OpenAI, augmented with Cogni memory.
 * OpenAPI spec version: 0.1.0
 */

/**
 * ID of the parent block in the hierarchy (foreign key to memory_blocks.id)
 */
export type MemoryBlockParentId = string | null;
