/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cogni API
 * A minimal FastAPI that directly passes user queries to OpenAI, augmented with Cogni memory.
 * OpenAPI spec version: 0.1.0
 */
import type { NamespaceInfoDescription } from './namespaceInfoDescription';

/**
 * Information about a single namespace.
 */
export interface NamespaceInfo {
  /** Namespace ID */
  id: string;
  /** Human-readable namespace name */
  name: string;
  /** URL-safe namespace identifier */
  slug: string;
  /** ID of the namespace owner */
  owner_id: string;
  /** When namespace was created */
  created_at: string;
  /** Optional namespace description */
  description?: NamespaceInfoDescription;
  /** Whether the namespace is active */
  is_active?: boolean;
}
