/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cogni API
 * A minimal FastAPI that directly passes user queries to OpenAI, augmented with Cogni memory.
 * OpenAPI spec version: 0.1.0
 */
import type { NamespacesResponseRequestedBranch } from './namespacesResponseRequestedBranch';
import type { NamespaceInfo } from './namespaceInfo';

/**
 * Enhanced response for namespaces endpoint that includes current context.
Uses proper NamespaceInfo typing for frontend TypeScript generation.
 */
export interface NamespacesResponse {
  /** Currently active Dolt branch for this operation */
  active_branch: string;
  /** Branch requested by client (may differ from active_branch for read operations) */
  requested_branch?: NamespacesResponseRequestedBranch;
  /** UTC ISO timestamp when the operation was performed */
  timestamp: string;
  /** List of all available namespaces with metadata */
  namespaces: NamespaceInfo[];
  /** Total number of namespaces available */
  total_count: number;
}
