/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cogni API
 * A minimal FastAPI that directly passes user queries to OpenAI, augmented with Cogni memory.
 * OpenAPI spec version: 0.1.0
 */
import type { BlockLink } from './blockLink';
import type { PaginatedLinksResponseNextCursor } from './paginatedLinksResponseNextCursor';
import type { PaginatedLinksResponseTotalAvailable } from './paginatedLinksResponseTotalAvailable';

/**
 * Response model for paginated links.
 */
export interface PaginatedLinksResponse {
  links: BlockLink[];
  next_cursor?: PaginatedLinksResponseNextCursor;
  /** Number of items in this page */
  page_size: number;
  /** Total count (if cheaply computable) */
  total_available?: PaginatedLinksResponseTotalAvailable;
}
