/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cogni API
 * A minimal FastAPI that directly passes user queries to OpenAI, augmented with Cogni memory.
 * OpenAPI spec version: 0.1.0
 */
import type { SingleBlockResponseRequestedBranch } from './singleBlockResponseRequestedBranch';
import type { MemoryBlock } from './memoryBlock';

/**
 * Enhanced response for single block retrieval with branch context.
Uses proper MemoryBlock typing for frontend TypeScript generation.
 */
export interface SingleBlockResponse {
  /** Currently active Dolt branch for this operation */
  active_branch: string;
  /** Branch requested by client (may differ from active_branch for read operations) */
  requested_branch?: SingleBlockResponseRequestedBranch;
  /** UTC ISO timestamp when the operation was performed */
  timestamp: string;
  /** The requested memory block */
  block: MemoryBlock;
}
