/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cogni API
 * A minimal FastAPI that directly passes user queries to OpenAI, augmented with Cogni memory.
 * OpenAPI spec version: 0.1.0
 */


/**
 * Health check endpoint for monitoring.
 * @summary Health Check
 */
export type healthCheckHealthzGetResponse200 = {
  data: unknown
  status: 200
}
    
export type healthCheckHealthzGetResponseComposite = healthCheckHealthzGetResponse200;
    
export type healthCheckHealthzGetResponse = healthCheckHealthzGetResponseComposite & {
  headers: Headers;
}

export const getHealthCheckHealthzGetUrl = () => {


  

  return `/healthz`
}

export const healthCheckHealthzGet = async ( options?: RequestInit): Promise<healthCheckHealthzGetResponse> => {
  
  const res = await fetch(getHealthCheckHealthzGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: healthCheckHealthzGetResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as healthCheckHealthzGetResponse
}


