/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cogni API
 * A minimal FastAPI that directly passes user queries to OpenAI, augmented with Cogni memory.
 * OpenAPI spec version: 0.1.0
 */
import type {
  BranchesResponse,
  ErrorResponse
} from './models';



/**
 * Retrieves list of all available Dolt branches with their metadata including commit information, status, and active branch context.
 * @summary Get all Dolt branches with context
 */
export type getAllBranchesApiV1BranchesGetResponse200 = {
  data: BranchesResponse
  status: 200
}

export type getAllBranchesApiV1BranchesGetResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type getAllBranchesApiV1BranchesGetResponseComposite = getAllBranchesApiV1BranchesGetResponse200 | getAllBranchesApiV1BranchesGetResponse500;
    
export type getAllBranchesApiV1BranchesGetResponse = getAllBranchesApiV1BranchesGetResponseComposite & {
  headers: Headers;
}

export const getGetAllBranchesApiV1BranchesGetUrl = () => {


  

  return `/api/v1/branches`
}

export const getAllBranchesApiV1BranchesGet = async ( options?: RequestInit): Promise<getAllBranchesApiV1BranchesGetResponse> => {
  
  const res = await fetch(getGetAllBranchesApiV1BranchesGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getAllBranchesApiV1BranchesGetResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getAllBranchesApiV1BranchesGetResponse
}


