/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Cogni API
 * A minimal FastAPI that directly passes user queries to OpenAI, augmented with Cogni memory.
 * OpenAPI spec version: 0.1.0
 */
import type {
  ErrorResponse,
  NamespacesResponse
} from './models';



/**
 * Retrieves list of all available namespaces with their metadata including creation information, ownership, and active status.
 * @summary Get all available namespaces with context
 */
export type getAllNamespacesApiV1NamespacesGetResponse200 = {
  data: NamespacesResponse
  status: 200
}

export type getAllNamespacesApiV1NamespacesGetResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type getAllNamespacesApiV1NamespacesGetResponseComposite = getAllNamespacesApiV1NamespacesGetResponse200 | getAllNamespacesApiV1NamespacesGetResponse500;
    
export type getAllNamespacesApiV1NamespacesGetResponse = getAllNamespacesApiV1NamespacesGetResponseComposite & {
  headers: Headers;
}

export const getGetAllNamespacesApiV1NamespacesGetUrl = () => {


  

  return `/api/v1/namespaces`
}

export const getAllNamespacesApiV1NamespacesGet = async ( options?: RequestInit): Promise<getAllNamespacesApiV1NamespacesGetResponse> => {
  
  const res = await fetch(getGetAllNamespacesApiV1NamespacesGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getAllNamespacesApiV1NamespacesGetResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getAllNamespacesApiV1NamespacesGetResponse
}


